### PR TITLE
Fix isArray when null is passed

### PR DESCRIPTION
**Pull request by naturalethic**
`typeof null` resolves to `'object'` so a further test is needed to insure the value is not null.

### CODE REVIEW

**Comment by mariocasciaro** [comment]
Hey thanks for the PR. I think `obj != null` would be better as it would also catch the case in which `obj` is undefined. Could you please make the small change?

**Comment by naturalethic** [comment]
Yep.  There you go.

**Comment by xgbuils** [comment]
>Hey thanks for the PR. I think obj != null would be better as it would also catch the case in which obj is >undefined. Could you please make the small change?

If is `obj === undefined`, then `typeof obj !== 'object'`. So it is redundant catch the case in which obj is `undefined`

A short way to check if is it an Array: https://github.com/juliangruber/isarray/blob/master/index.js

**Comment by mariocasciaro** [comment]
@xgbuils I know it is redundant, but it could be slightly faster... However, I like that implementation of isArray you linked, ultimately I think we should switch completely to Array.isArray at some point, but I guess that a fallback function would be appropriate for compatibility.

@naturalethic I'm sorry to ask you again, but could you please change the entire function to look like the one in the link? (Note: consider that we already have a `toStr` function available to use in the code, so no need to obtain it again)

**Comment by naturalethic** [comment]
Done.  Note I had to change it to an anonymous rather than named/hoisted function.  Tests passing.

**Comment by mariocasciaro** [comment]
Looks good thanks!

**Pull request merged**
